# Aufbau einer Datenbank aus nicht-normalisierten Daten

Schritt 1: Normalisieren des Excel-Tabellenblatts
Der erste Schritt des SQL-Projekts besteht darin, eine große Excel-Tabelle mit redundanten
Werten zu normalisieren. Führe die folgenden Aufgaben durch:
• Öffne das Excel-Tabellenblatt.
• Identifiziere die redundanten Werte und bestimme die geeigneten
Normalisierungsschritte.
• Normalisiere die Daten, indem du separate Tabellen erstellst, was du in Excel (csvs
erstellen) oder bereits in SQL machen kannst.

### Imports

In [8]:
import pandas as pd
import re
from datetime import datetime

### Ausgangs-Tabelle einpflegen

In [ ]:
ausgang_df = pd.read_excel("03_nicht_normalisierte_Daten.xlsx", sheet_name="Ausgangstabelle", engine="openpyxl")

ausgang_df

,BestellID,Menge,Bestelldatum,KundeName,KundeAdresse,KundeKreditkarte,ProduktnameName,ProduktPreis,Kategorie
0,1,6,30.09.2022,Heddi Radford,"Hauptstrasse 107, 91054 Erlangen",5443412551823880,Fellowes Aktenvernichter,35,Bürobedarf
1,2,7,06.02.2023,Kim Dowsey,"Munchenstrasse 45, 38120 Braunschweig",5386779659180120,Der Herr der Ringe,100,Bücher
2,3,4,16.12.2022,Edy Delea,"Burgplatz 2, 72764 Reutlingen",5273849209977540,Michelin Pilot Sport 4 Reifen,150,Auto und Motorrad
3,4,8,31.07.2022,Krissie Saunper,"Heinrichstrasse 30, 07545 Gera",5589388672263750,Moleskine Classic Notizbuch,13,Bürobedarf
4,5,7,05.02.2023,Edy Delea,"Burgplatz 2, 72764 Reutlingen",5273849209977540,Game of Thrones: Die komplette Serie (DVD-Boxset),150,Filme und Serien
...,...,...,...,...,...,...,...,...,...
95,96,7,2021-03-28 00:00:00,Sidnee Jackalin,"Rudolf-Bultmann-Strasse 2, 35039 Marburg",5508107536078630,Netflix Premium-Abonnement,16,Filme und Serien
96,97,8,2020-10-21 00:00:00,Linnet Firmage,"Stockumer Strasse 171, 44225 Dortmund",5406252550077780,Rolex Submariner Herrenuhr,15000,Uhren
97,98,2,2021-09-04 00:00:00,Heddi Radford,"Hauptstrasse 107, 91054 Erlangen",5443412551823880,Swarovski Crystal Ohrringe,170,Schmuck
98,99,3,2021-07-15 00:00:00,Alla Mawne,"Kavalierhaus am Schlosspark, 16831 Rheinsberg",5314574774112590,Trixie Kratzbaum für Katzen,200,Tierbedarf
99,100,6,2021-09-02 00:00:00,See Dorman,"Oester 1, 33428 Harsewinkel",5132364984299640,David Yurman Cable Classic Armreif,300,Schmuck

### Produkt-Tabelle einpflegen

In [ ]:
produkte_df = pd.read_excel("03_nicht_normalisierte_Daten.xlsx", sheet_name="Produkte", engine="openpyxl")

produkte_df.to_csv("produkte.csv", index=False)

produkte_df

,ProduktID,ProduktName,ProduktPreis,Kategorie
0,1,Adidas Ultraboost Sneakers,90,Kleidung
1,2,Alex and Ani Birthstone Halskette,60,Schmuck
2,3,Apple MacBook Pro Laptop,1100,Computer und Zubehör
3,4,BabyBjörn Baby Carrier,220,Baby
4,5,Bulgari Serpenti Diamond Ring,10500,Schmuck
5,6,Clarisonic Mia 2 Gesichtsreinigungsbürste,155,Schönheit und Pflege
6,7,Coleman Campingzelt,140,Sport und Freizeit
7,8,David Yurman Cable Classic Armreif,300,Schmuck
8,9,Der Herr der Ringe,100,Bücher
9,10,Dyson V11 Absolute Staubsauger,530,Haushalt
10,11,Eames Lounge Chair,6200,Möbel
11,12,Fellowes Aktenvernichter,35,Bürobedarf
12,13,Fender Stratocaster E-Gitarre,750,Musikinstrumente
13,14,Fisher-Price Infant-to-Toddler Rocker,56,Baby
14,15,Fitbit Charge 4 Fitness-Tracker,265,Gesundheit und Wellness
15,16,Frontline Plus Floh- und Zeckenschutz für Hunde,25,Tierbedarf
16,17,Game of Thrones: Die komplette Serie (DVD-Boxset),150,Filme und Serien
17,18,Garmin Forerunner 245 GPS-Laufuhr,160,Sport und Freizeit
18,19,Graco Pack 'n Play Portable Playard,77,Baby
19,20,HP LaserJet Pro Drucker,160,Bürobedarf
20,21,Ikea Malm Kommode,50,Möbel
21,22,Instant Pot Duo Plus Schnellkochtopf,120,Haushalt
22,23,LEGO Star Wars Millennium Falcon Set,200,Spielzeug und Spiele
23,24,Levi's 501 Jeans,190,Kleidung
24,25,Marvel's Avengers: Endgame (Blu-ray),20,Filme und Serien
25,26,Michelin Pilot Sport 4 Reifen,150,Auto und Motorrad
26,27,Moleskine Classic Notizbuch,13,Bürobedarf
27,28,Netflix Premium-Abonnement,16,Filme und Serien
28,29,Pampers Swaddlers Diapers,8,Baby
29,30,Pandora Charm-Armband,18,Schmuck
30,31,Philips Sonicare elektrische Zahnbürste,85,Gesundheit und Wellness
31,32,Rolex Submariner Herrenuhr,15000,Uhren
32,33,Royal Canin Adult Trockenfutter für Katzen,20,Tierbedarf
33,34,Samsung Galaxy S21 Smartphone,175,Elektronik
34,35,Staedtler Triplus Fineliner Stifte,7,Bürobedarf
35,36,Swarovski Crystal Ohrringe,170,Schmuck
36,37,TAG Heuer Carrera Chronograph,230,Uhren
37,38,Tiffany & Co. Diamant-Verlobungsring,700,Schmuck
38,39,Trixie Kratzbaum für Katzen,200,Tierbedarf
39,40,Wilson Pro Staff Tennisschläger,80,Sport und Freizeit
40,41,WMF Besteckset Miami,100,Küche und Esszimmer
41,42,Zara Trenchcoat,130,Kleidung

### Kunden-Tabelle einpflegen

In [ ]:
kunden_df = pd.read_excel("03_nicht_normalisierte_Daten.xlsx", sheet_name="Kunden", engine="openpyxl")

kunden_df.to_csv("kunden.csv", index=False)

kunden_df

,KundenID,KundeName,KundeAdresse,KundeKreditkarte
0,1,Alla Mawne,"Kavalierhaus am Schlosspark, 16831 Rheinsberg",5314574774112590
1,2,Barret Aaronson,"Habsburgerstrasse 133, 79104 Freiburg im Breisgau",5410033003668250
2,3,Bobbee McClaren,"Potsdamer Strasse 46, 14469 Potsdam",5270254082243370
3,4,Celeste Lidington,"Am Eckey 3, 58239 Schwerte",5514830264595360
4,5,Dario Pavis,"Michaelisstrasse 44, 99084 Erfurt",5282418605703000
5,6,Dorella Eles,"Kaiserstrasse 73, 45699 Herten",5152056017234780
6,7,Edee Mattedi,"Kasernstrasse 4-6, 86152 Augsburg",5395802826980750
7,8,Edy Delea,"Burgplatz 2, 72764 Reutlingen",5273849209977540
8,9,Fernanda Larcier,"Kirchhofsweg 53 B, 25421 Pinneberg",5236195016854390
9,10,Glenna Ettritch,"Max-von-Laue-Strasse 9, 60439 Frankfurt am Main",5188219748299840
10,11,Heddi Radford,"Hauptstrasse 107, 91054 Erlangen",5443412551823880
11,12,Helen-elizabeth Liddell,"Gerhardswinkel 1, 53572 Unkel",5452530720864080
12,13,Inge Wyleman,"Nageleseestrasse 3, 79102 Freiburg im Breisgau",5372767251150500
13,14,Iolanthe Dreakin,"Karlstrasse 28, 76133 Karlsruhe",5115750948900930
14,15,Karlen Holby,"Sandwelle 10, 59494 Soest",5585728810236310
15,16,Kim Dowsey,"Munchenstrasse 45, 38120 Braunschweig",5386779659180120
16,17,Kirby Poxon,"Friedrich-Wohler-Strasse 2, 64579 Gernsheim",5235734980328510
17,18,Krissie Saunper,"Heinrichstrasse 30, 07545 Gera",5589388672263750
18,19,Linnet Firmage,"Stockumer Strasse 171, 44225 Dortmund",5406252550077780
19,20,Lorelei Tal,"Basler Strasse 10, 79189 Bad Krozingen",5126703055317810
20,21,Mannie Hendricks,"Trierer Strasse 282, 56072 Koblenz",5473450221585970
21,22,Neile Patinkin,"Marktstrasse 30, 73207 Plochingen",5518441858555480
22,23,Noelyn Sorel,"Mummendorfer Weg 11, 23769 Fehmarn",5157168399114020
23,24,Orton Tye,"Berliner Strasse 269, 65205 Wiesbaden",5472347033020320
24,25,Rozanna Trathen,"Donaustrasse 8, 85049 Ingolstadt",5249731309556310
25,26,Ruy McCarry,"Adenauerallee 209, 52066 Aachen",5295286000737500
26,27,See Dorman,"Oester 1, 33428 Harsewinkel",5132364984299640
27,28,Sidnee Jackalin,"Rudolf-Bultmann-Strasse 2, 35039 Marburg",5508107536078630
28,29,Toby Mancktelow,"Carl-Benz-Strasse 21, 60386 Frankfurt am Main",5137727097274260
29,30,Torin Langabeer,"Oranienstrasse 4, 65185 Wiesbaden",5489445526392380

### Verkäufe-Tabelle einpflegen

In [7]:
verkaeufe_df = pd.read_excel("03_nicht_normalisierte_Daten.xlsx", sheet_name="Verkäufe", engine="openpyxl")

verkaeufe_df.to_csv("verkaeufe.csv", index=False)

verkaeufe_df

    BestellID  Menge         Bestelldatum  KundenID  ProduktID
0           1      8  2020-10-21 00:00:00        19         32
1           2      3  2021-01-22 00:00:00         2         33
2           3      5  2021-02-10 00:00:00         8         27
3           4      4  2021-02-11 00:00:00         6         28
4           5      1  2021-03-11 00:00:00         7          9
..        ...    ...                  ...       ...        ...
95         96      5           13.05.2023         9         37
96         97      4  2023-05-13 00:00:00        27         20
97         98      9           17.05.2023         8         20
98         99      6           21.05.2023        28          3
99        100      1  2023-06-04 00:00:00         1         23

[100 rows x 5 columns]

### Bereinigte Verkäufe-Tabelle

In [ ]:
# CSV-Datei laden
df = pd.read_csv("verkaeufe.csv")

# Funktion zur Umwandlung von Datumswerten
def parse_datum(value):
    value = str(value).strip()

    # Überprüfung und Umwandlung des Datumsformats: DD.MM.YYYY
    if re.fullmatch(r"\d{2}\.\d{2}\.\d{4}", value):
        parts = value.split(".")
        return f"{parts[2]}-{parts[1]}-{parts[0]}"

    # Überprüfung und Rückgabe im Datumsformat: YYYY-MM-DD (ISO-Format)
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        return value

    # Überprüfung auf Datum mit Zeitangabe (YYYY-MM-DD HH:MM:SS oder YYYY-MM-DD HH:MM)
    # Nur der Datumsteil wird extrahiert
    if re.fullmatch(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}(:\d{2})?", value):
        return value.split(" ")[0]

    # Wenn der Wert keinem bekannten Datumsformat entspricht, unverändert zurückgeben
    return value

# Funktion auf die Spalte 'Bestelldatum' anwenden
df["Bestelldatum"] = df["Bestelldatum"].apply(parse_datum)

# Bereinigte Daten in eine neue CSV-Datei speichern
df.to_csv("verkaeufe_bereinigt.csv", index=False)